name: deploy
on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: setup golang
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - uses: actions/checkout@v1

    - name: get dependencies
      run: make dep
      
    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.27.0

    - name: run linter
      run: $(go env GOPATH)/bin/golangci-lint run

    - name: build
      run: CGO_ENABLED=0 make build

    - name: golangci-lint
      run: $(go env GOPATH)/bin/golangci-lint run

    - uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY }}  
        repository: delgus/ai-bot
        tags: latest
      
    - uses: appleboy/ssh-action@v0.0.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PSW }}
        script: | 
          docker pull ${{ secrets.DOCKER_REGISTRY }}/delgus/ai-bot
          docker rm --force ai-bot  
          docker run --name=ai-bot -d --restart unless-stopped -e CREDENTIALS_JSON=${{ secrets.CREDENTIALS_JSON }} -e ORIGINAL_URL=${{ secrets.ORIGINAL_URL }} -e PROJECT_ID=${{ secrets.PROJECT_ID }} -e WS_URL=${{ secrets.WS_URL }} delgus/ai-bot
          
