name: deploy
on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2
      
    - uses: golangci/golangci-lint-action@v1
      with:
          version: v1.27

    - name: build
      run: CGO_ENABLED=0 make build

    - uses: docker/build-push-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        #registry: ${{ secrets.DOCKER_REGISTRY }}  
        repository: delgus/ai-bot
        tags: latest

    - uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: tcp://${{ secrets.HOST }}:2376
        args: stack deploy -c deploy.yml ai
      env:
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        WS_URL: ${{ secrets.WS_URL }}
          
